version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: ewallet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ewallet
      POSTGRES_PASSWORD: ewallet_secret
      POSTGRES_DB: ewallet_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
